### ISSUE TITLE
Need v1.0.0 as a dependency for signalrcore

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/websocket-client-feedstock#49]
I maintain the signalrcore feedstock and a recent update requires v1.0.0 of websocket-client, which is not available. I'm not 100% sure what the procedure is to get an older version of a package, but I think it requires creating a new branch for that specific version. I'm happy to assist in any way.

**Comment by BastianZim** [comment]
Hi @synapticarbors if you only need that version we can just merge it into main. But if you think that you'll probably need some others as well, I can create a separate branch.

Anyways, the process with both is a PR with `v1.0.0` and we can then either merge it into a separate branch or main, depending on what you need. Can you therefore please create the PR, happy to help if you have any questions.

**Comment by synapticarbors** [comment]
Thanks. I've opened #50 to address this

**Comment by BastianZim** [comment]
Great! Do you only need this one or do you think some other versions will also be required?

**Comment by synapticarbors** [comment]
At this point, only this version. I'm not sure why the signalrcore developer went with releasing off of this strictly pinned version or which version they might require in subsequent releases, but this should get us up-to-date for now.

**Comment by BastianZim** [comment]
Ok sounds good. Just ping me when you’re ready.
